# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trpc.proto\x12\x07twigrpc\"4\n\x0bRpcResponse\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\x14\n\x0c\x65rror_detail\x18\x02 \x01(\t\"[\n\x08Instance\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\x13\n\x0binstance_id\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\r\x12\x0f\n\x07healthy\x18\x05 \x01(\x08\"\"\n\x0f\x44iscoverRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"I\n\x10\x44iscoverResponse\x12$\n\tinstances\x18\x01 \x03(\x0b\x32\x11.twigrpc.Instance\x12\x0f\n\x07version\x18\x02 \x01(\x04\"\'\n\x10HeartbeatRequest\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\"\x1f\n\x11HeartbeatResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RPCRESPONSE._serialized_start=22
  _RPCRESPONSE._serialized_end=74
  _INSTANCE._serialized_start=76
  _INSTANCE._serialized_end=167
  _DISCOVERREQUEST._serialized_start=169
  _DISCOVERREQUEST._serialized_end=203
  _DISCOVERRESPONSE._serialized_start=205
  _DISCOVERRESPONSE._serialized_end=278
  _HEARTBEATREQUEST._serialized_start=280
  _HEARTBEATREQUEST._serialized_end=319
  _HEARTBEATRESPONSE._serialized_start=321
  _HEARTBEATRESPONSE._serialized_end=352
# @@protoc_insertion_point(module_scope)
